new: Added a new lab 'Mountpoint for S3'
aws-samples/eks-workshop-v2 pull request #1176
Opened 2024-11-04 17:30 UTC by rchandra20

#### What this PR does / why we need it:

EKS Workshop can benefit greatly from a module that showcases the use of Mountpoint for S3. This content is placed under the Fundamentals/Storage exercises. 

#### Which issue(s) this PR fixes: Fixes #843

#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test module="fundamentals/storage/mountpoint-s3"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
- [x] The PR has meaningful title and description of the changes that will be included in the workshop release notes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-04 19:31 UTC, heinrichse submitted a review, later dismissed
Reviewed and approved PR

2024-11-04 20:15 UTC, heinrichse submitted a review, later dismissed

2024-11-05 19:32 UTC, heinrichse submitted a review, later dismissed
Reviewed and approved

2024-11-15 01:21 UTC, pengc99 reviewed
Reviewed this in rchandra20's repo already - this content is ready to be merged from my end. Would appreciate a second look.

2024-11-15 19:45 UTC, niallthomson requested changes
Looks great overall, noted some changes I think we should make

2024-12-16 21:12 UTC, rchandra20 commented on website/docs/fundamentals/storage/mountpoint-s3/30-persistent-object-storage-with-mountpoint-for-amazon-s3.md
> +```file
[Removed comments on s3pvclaim.yaml](https://github.com/aws-samples/eks-workshop-v2/pull/1176/commits/b9e0f10731d32d9f3df210e43fa0ecb3d85f1643)

2024-12-16 21:37 UTC, rchandra20 commented on website/docs/fundamentals/storage/mountpoint-s3/10-ephemeral-container-storage.md
> +```bash
Trimmed down deployment section in 'Ephemeral Container Storage'

2024-12-16 21:38 UTC, rchandra20 commented on website/docs/fundamentals/storage/mountpoint-s3/30-persistent-object-storage-with-mountpoint-for-amazon-s3.md
> +Finally, let's take a look at our final deployment with the Mountpoint for Amazon S3 CSI driver:
[Used YAML UI component, described PVC, and trimmed deployment informa…](https://github.com/aws-samples/eks-workshop-v2/pull/1176/commits/f924839b85389fa9f72253445a623d9ddf909d96) 
[f924839](https://github.com/aws-samples/eks-workshop-v2/pull/1176/commits/f924839b85389fa9f72253445a623d9ddf909d96)
…tion

2024-12-20 18:23 UTC, merged