new: troubleshooting module - All scenarios
aws-samples/eks-workshop-v2 pull request #1182
Opened 2024-11-20 13:49 UTC by arcegacardenas

#### What this PR does / why we need it:
This is a new module that helps troubleshoot common EKS scenarios. 

#### Which issue(s) this PR fixes:

Fixes #906

#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md) **I ran each lab within the module individually due to a sts token expiration issue** To make able to simulate the scenarios I had to test each individually.
- [x] The PR has meaningful title and description of the changes that will be included in the workshop release notes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-04-22 19:14 UTC, svennam92 requested changes

2025-04-22 19:14 UTC, svennam92 commented on manifests/modules/troubleshooting/dns/.workshop/cleanup.sh
> +    --cluster-name eks-workshop \
cluster name should be env var

2025-04-22 19:14 UTC, svennam92 commented on manifests/modules/troubleshooting/workernodes/.workshop/cleanup.sh
> +        --cluster-name eks-workshop \
env var

2025-04-22 19:14 UTC, svennam92 commented on manifests/modules/troubleshooting/workernodes/.workshop/cleanup.sh
> +if aws eks describe-nodegroup --cluster-name eks-workshop --nodegroup-name new_nodegroup_3 >/dev/null 2>&1; then
env var for cluster name

2025-04-23 15:56 UTC, robisoh88 commented on manifests/modules/troubleshooting/workernodes/.workshop/cleanup.sh
> +if aws eks describe-nodegroup --cluster-name eks-workshop --nodegroup-name new_nodegroup_3 >/dev/null 2>&1; then
Updated

2025-04-23 15:56 UTC, robisoh88 commented on manifests/modules/troubleshooting/workernodes/.workshop/cleanup.sh
> +        --cluster-name eks-workshop \
Updated

2025-04-23 15:56 UTC, robisoh88 commented on manifests/modules/troubleshooting/dns/.workshop/lab-setup.sh
> +    --cluster-name eks-workshop \
Updated

2025-04-23 15:56 UTC, robisoh88 commented on manifests/modules/troubleshooting/dns/.workshop/cleanup.sh
> +    --cluster-name eks-workshop \
Updated

2025-04-24 15:42 UTC, svennam92 approved these changes
LGTM

2025-04-24 15:43 UTC, merged